# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c47242195ae6a8c638c6ebe5b33726089ac660be08591c63192a15901bd988084012df7db3c2b46caff9d666f573a7a2783605552f3186f1e52436b059eeb30

test:
  secret_key_base: 3e0a8117fb5c2ae822aa5ab4c4d985ab8733aaacf02470bdc159a9eaed8dc174dd63e9dad3db936b0e23bcbdf6a491d09ce8744038fe76405aa0f51f3e1a1ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
